services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: |
        mongosh --eval "
        try {
          rs.status();
          printjson({ok: 1});
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [{_id: 0, host: 'mongodb:27017'}]
          });
        }"
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s